[package]
name = "bevy_kira_audio"
version = "0.3.0"
authors = ["Niklas Eicker <hello@nikl.me>"]
edition = "2018"
license = "MIT"
description = "Bevy plugin for dynamic audio"
repository = "https://github.com/NiklasEi/bevy_kira_audio"
homepage = "https://github.com/NiklasEi/bevy_kira_audio"
documentation = "https://github.com/NiklasEi/bevy_kira_audio"
keywords = ["bevy", "gamedev", "audio", "music"]
categories = ["game-development", "multimedia::audio"]
readme = "./README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
mp3 = ["minimp3"]
ogg = ["lewton"]
flac = ["claxon"]
wav = ["hound"]
example = [
    "bevy/bevy_gltf",
    "bevy/bevy_winit",
    "bevy/render",
    "bevy/png",
    "bevy/bevy_wgpu",
    "ogg"
]

[dependencies]
# bevy
bevy = { git = "https://github.com/bevyengine/bevy/", rev="d021a3c3748ca921fa7c0aa94bfb09e6f30090d0", default-features = false }
bevy_reflect = { git = "https://github.com/bevyengine/bevy/", rev="d021a3c3748ca921fa7c0aa94bfb09e6f30090d0" }

# other
anyhow = "1.0"
kira = { version="0.4.1", default-features=false }
parking_lot = "0.11.0"

minimp3 = { version = "0.5.0", optional=true }
claxon = { version = "0.4.3", optional = true }
hound = { version = "3.4.0", optional = true }
lewton = { version = "0.10.1", optional = true }

[dev-dependencies]
winit = "0.24.0"

[[example]]
name = "basic"
path = "examples/basic.rs"
required-features = ["example"]
